# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
  
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: blog_app
          MYSQL_USER: blog_app
          MYSQL_PASSWORD: 5678

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Run tests
      env:
        MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
      run: TEST_DATABASE_URL="mysql+aiomysql://blog_app:5678@127.0.0.1:${MYSQL_PORT}/blog_app" poetry run pytest --doctest-modules --cov=blog_app --cov-report=term --cov-report=html
