# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: blog_app
          MYSQL_USER: blog_app
          MYSQL_PASSWORD: 5678
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Run tests
      env:
        MYSQL_PORT = ${{ job.services.mysql.ports[3306] }}
        TEST_DATABASE_URL = "mysql+aiomysql://blog_app:5678@127.0.0.1:$PORT/blog_app_test"
      run: poetry run pytest --doctest-modules --cov=blog_app --cov-report=term --cov-report=html
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
